#!/bin/sh
. ./setting
if [ ! "$UID" == "0" ]
then 
	echo "root privilege required!try \"sudo ./install \" now exit..."
	exit
fi
cp -rp $sourcedir $installdir
cp -p $sourcedir/proton $installdir/proton.py
cp -pf proton $installdir
chmod +x $installdir/proton
chmod -R 755 $installdir
ln -s $installdir/proton /usr/bin
echo install complete
echo useage : proton run {path to exe}