#!/bin/sh
. ./setting
if [ ! "$UID" == "0" ]
then 
	echo "root privilege required!try \"sudo ./install \" now exit..."
	exit
fi
mv ./$sourcedir/proton ./sourcedir/proton.py
cp proton ./$sourcedir
chmod +x ./proton
cp $sourcedir $installdir
chmod -R 755 $installdir
ln -s $installdir/proton /usr/bin
echo install complete
echo useage : proton run {path to exe}

